# Generated by Django 4.2.7 on 2024-09-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="item",
            field=models.CharField(default="Add Item", max_length=50),
            preserve_default=False,
        ),
    ]
