# Generated by Django 4.2.7 on 2024-09-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_order_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="email",
            field=models.EmailField(
                default="Please insert your email", max_length=254, unique=True
            ),
            preserve_default=False,
        ),
    ]
