# Generated by Django 4.2.7 on 2024-09-22 08:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_customer_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
