name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
      DEBUG: ${{ secrets.DEBUG }}
      POSTGRES_ENGINE: ${{ secrets.POSTGRES_ENGINE }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      PG_HOST: localhost
      PG_PORT: 5432
      AFRICASTALKING_API_KEY: ${{ secrets.AFRICASTALKING_API_KEY }}
      AFRICASTALKING_USERNAME: ${{ secrets.AFRICASTALKING_USERNAME }}
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        python manage.py test
    - name: Run coverage
      run: |
        pip install coverage
        coverage run manage.py test
        coverage report

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "savinfo"
        heroku_email: "ekibet544@gmail.com"
    - name: Run database migrations
      run: |
        heroku run python manage.py migrate --app savinfo
    - name: Health check
      run: |
        curl -f https://savinfo-46ec763fcf87.herokuapp.com//health || exit 1
    - name: Tag the release
      run: |
        git tag -a v$(date +'%Y%m%d%H%M%S') -m "Deployed to Heroku"
        git push origin --tags     
