name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    # Install dependencies, including coverage
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage  # install coverage together with dependencies

    # Set environment variables (before running tests)
    - name: Set environment variables
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}

    # Run tests
    - name: Run tests
      run: |
        python manage.py test

    # Run coverage after tests
    - name: Run coverage
      run: |
        coverage run manage.py test
        coverage report

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
    - uses: actions/checkout@v2
    
   
